// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNL5ygIPtfWcemoFkOybcNp8TUBBvR2bE',
    appId: '1:819380946773:web:f76c3daf7ed0d6790b91dc',
    messagingSenderId: '819380946773',
    projectId: 'releanstask',
    authDomain: 'releanstask.firebaseapp.com',
    storageBucket: 'releanstask.appspot.com',
    measurementId: 'G-PW11BY6J7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq2F-2xDRR7SCbR_RkiWTpKbrSH_UQ_nI',
    appId: '1:819380946773:android:96a0c9bbe8bd057f0b91dc',
    messagingSenderId: '819380946773',
    projectId: 'releanstask',
    storageBucket: 'releanstask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDARketQOUemtgKRzNrfPQhoTaAtep41ig',
    appId: '1:819380946773:ios:e2a14562521c661e0b91dc',
    messagingSenderId: '819380946773',
    projectId: 'releanstask',
    storageBucket: 'releanstask.appspot.com',
    iosBundleId: 'com.example.releansTask',
  );
}
